#import "GDTStores.h"
#import <sqlite3.h>

static NSString *const GDTSessionPrefix = @"GoogleDocsTTS.session.";
static NSString *const GDTBookmarkPrefix = @"GoogleDocsTTS.bookmarks.";
@implementation GDTUserDefaultsStore
- (GDTReadingSession *)sessionForDocument:(NSString *)documentID { NSData *data = [[NSUserDefaults standardUserDefaults] objectForKey:[GDTSessionPrefix stringByAppendingString:documentID]]; return data ? [NSKeyedUnarchiver unarchivedObjectOfClass:GDTReadingSession.class fromData:data error:nil] : ({ GDTReadingSession *s=[GDTReadingSession new]; s.documentID=documentID; s.rate=0.5f; s.state=GDTReadingStateIdle; s; }); }
- (void)saveSession:(GDTReadingSession *)session { NSData *data = [NSKeyedArchiver archivedDataWithRootObject:session requiringSecureCoding:YES error:nil]; if (data) [[NSUserDefaults standardUserDefaults] setObject:data forKey:[GDTSessionPrefix stringByAppendingString:session.documentID]]; }
- (void)saveBookmarkForDocument:(NSString *)documentID sentenceIndex:(NSUInteger)index { GDTPlaybackPosition *position=[GDTPlaybackPosition new]; position.documentID=documentID; position.sentenceIndex=index; position.timestamp=NSDate.date; [self saveBookmark:position]; }
- (NSArray<NSNumber *> *)bookmarksForDocument:(NSString *)documentID { NSMutableArray *result=[NSMutableArray array]; for (GDTPlaybackPosition *position in [self bookmarkPositionsForDocument:documentID]) [result addObject:@(position.sentenceIndex)]; return result; }
- (void)saveBookmark:(GDTPlaybackPosition *)position { NSString *key=[GDTBookmarkPrefix stringByAppendingString:position.documentID]; NSMutableArray *stored=[([NSUserDefaults.standardUserDefaults arrayForKey:key] ?: @[]) mutableCopy]; NSData *data=[NSKeyedArchiver archivedDataWithRootObject:position requiringSecureCoding:YES error:nil]; if (data) [stored addObject:data]; [NSUserDefaults.standardUserDefaults setObject:stored forKey:key]; }
- (NSArray<GDTPlaybackPosition *> *)bookmarkPositionsForDocument:(NSString *)documentID { NSArray *stored=[NSUserDefaults.standardUserDefaults arrayForKey:[GDTBookmarkPrefix stringByAppendingString:documentID]] ?: @[]; NSMutableArray *result=[NSMutableArray array]; for (id item in stored) { if (![item isKindOfClass:NSData.class]) continue; GDTPlaybackPosition *position=[NSKeyedUnarchiver unarchivedObjectOfClass:GDTPlaybackPosition.class fromData:item error:nil]; if (position) [result addObject:position]; } return result; }
- (BOOL)saveDocument:(GDTDocument *)document error:(NSError **)error { NSData *data=[NSKeyedArchiver archivedDataWithRootObject:document requiringSecureCoding:YES error:error]; if (!data) return NO; NSString *key=[@"GoogleDocsTTS.document." stringByAppendingString:document.documentID]; [NSUserDefaults.standardUserDefaults setObject:data forKey:key]; return YES; }
- (GDTDocument *)documentForID:(NSString *)documentID contentHash:(NSString *)contentHash error:(NSError **)error { NSData *data=[NSUserDefaults.standardUserDefaults dataForKey:[@"GoogleDocsTTS.document." stringByAppendingString:documentID]]; if (!data) return nil; NSSet *classes=[NSSet setWithObjects:GDTDocument.class,GDTContentNode.class,GDTSection.class,GDTParagraph.class,GDTSentence.class,GDTWord.class,NSArray.class,NSDictionary.class,NSString.class, nil]; GDTDocument *document=[NSKeyedUnarchiver unarchivedObjectOfClasses:classes fromData:data error:error]; return [document.contentHash isEqualToString:contentHash] ? document : nil; }
- (void)recordHistoryForDocument:(NSString *)documentID position:(GDTPlaybackPosition *)position { NSData *data=[NSKeyedArchiver archivedDataWithRootObject:position requiringSecureCoding:YES error:nil]; if (data) [NSUserDefaults.standardUserDefaults setObject:data forKey:[@"GoogleDocsTTS.history." stringByAppendingString:documentID]]; }
- (NSArray<GDTPlaybackPosition *> *)historyForDocument:(NSString *)documentID limit:(NSUInteger)limit { NSData *data=[NSUserDefaults.standardUserDefaults dataForKey:[@"GoogleDocsTTS.history." stringByAppendingString:documentID]]; GDTPlaybackPosition *position=data ? [NSKeyedUnarchiver unarchivedObjectOfClass:GDTPlaybackPosition.class fromData:data error:nil] : nil; return position ? @[position] : @[]; }
- (GDTSettings *)settings { NSData *data=[NSUserDefaults.standardUserDefaults dataForKey:@"GoogleDocsTTS.settings"]; return data ? ([NSKeyedUnarchiver unarchivedObjectOfClass:GDTSettings.class fromData:data error:nil] ?: [GDTSettings new]) : [GDTSettings new]; }
- (void)saveSettings:(GDTSettings *)settings { NSData *data=[NSKeyedArchiver archivedDataWithRootObject:settings requiringSecureCoding:YES error:nil]; if (data) [NSUserDefaults.standardUserDefaults setObject:data forKey:@"GoogleDocsTTS.settings"]; }
- (void)recordStatisticsForDocument:(NSString *)documentID seconds:(NSTimeInterval)seconds words:(NSUInteger)words { NSDictionary *value=@{ @"seconds":@(seconds), @"words":@(words) }; [NSUserDefaults.standardUserDefaults setObject:value forKey:[@"GoogleDocsTTS.statistics." stringByAppendingString:documentID]]; }
@end

static NSError *GDTDatabaseError(sqlite3 *db, NSString *operation) { const char *message=db ? sqlite3_errmsg(db) : "database unavailable"; return [NSError errorWithDomain:@"GoogleDocsTTS.Database" code:db ? sqlite3_errcode(db) : -1 userInfo:@{NSLocalizedDescriptionKey:[NSString stringWithFormat:@"%@ failed: %s", operation, message] }]; }

@interface GDTSQLiteStore ()
@property(nonatomic) sqlite3 *database;
@property(nonatomic) dispatch_queue_t queue;
@end

@implementation GDTSQLiteStore
- (instancetype)initWithURL:(NSURL *)url error:(NSError **)error { if ((self=[super init])) { _queue=dispatch_queue_create("com.google.docs.tts.database", DISPATCH_QUEUE_SERIAL); int status=sqlite3_open_v2(url.path.UTF8String, &_database, SQLITE_OPEN_READWRITE|SQLITE_OPEN_CREATE|SQLITE_OPEN_FULLMUTEX, NULL); if (status != SQLITE_OK) { if (error) *error=GDTDatabaseError(_database, @"Open database"); if (_database) sqlite3_close(_database); return nil; } const char *schema="PRAGMA journal_mode=WAL; CREATE TABLE IF NOT EXISTS Documents (document_id TEXT PRIMARY KEY, content_hash TEXT NOT NULL, payload BLOB NOT NULL, updated_at REAL NOT NULL); CREATE TABLE IF NOT EXISTS Bookmarks (document_id TEXT NOT NULL, paragraph_index INTEGER NOT NULL, sentence_index INTEGER NOT NULL, word_index INTEGER NOT NULL, character_offset INTEGER NOT NULL, scroll_offset REAL NOT NULL, progress REAL NOT NULL, timestamp REAL NOT NULL, PRIMARY KEY(document_id, paragraph_index, sentence_index, word_index)); CREATE TABLE IF NOT EXISTS History (id INTEGER PRIMARY KEY AUTOINCREMENT, document_id TEXT NOT NULL, payload BLOB NOT NULL, created_at REAL NOT NULL); CREATE TABLE IF NOT EXISTS ReadingSessions (document_id TEXT PRIMARY KEY, payload BLOB NOT NULL, updated_at REAL NOT NULL); CREATE TABLE IF NOT EXISTS Voices (identifier TEXT PRIMARY KEY, name TEXT NOT NULL, language TEXT NOT NULL); CREATE TABLE IF NOT EXISTS Settings (id INTEGER PRIMARY KEY CHECK(id=1), payload BLOB NOT NULL); CREATE TABLE IF NOT EXISTS CacheMetadata (document_id TEXT PRIMARY KEY, content_hash TEXT NOT NULL, byte_count INTEGER NOT NULL, updated_at REAL NOT NULL); CREATE TABLE IF NOT EXISTS Statistics (document_id TEXT PRIMARY KEY, seconds REAL NOT NULL DEFAULT 0, words INTEGER NOT NULL DEFAULT 0, sessions INTEGER NOT NULL DEFAULT 0);"; char *message=NULL; status=sqlite3_exec(_database,schema,NULL,NULL,&message); if (status != SQLITE_OK) { if (error) *error=[NSError errorWithDomain:@"GoogleDocsTTS.Database" code:status userInfo:@{NSLocalizedDescriptionKey:message ? [NSString stringWithUTF8String:message] : @"Schema creation failed"}]; sqlite3_free(message); sqlite3_close(_database); return nil; } } return self; }
- (void)dealloc { if (_database) sqlite3_close(_database); }
- (BOOL)saveDocument:(GDTDocument *)document error:(NSError **)error { NSData *payload=[NSKeyedArchiver archivedDataWithRootObject:document requiringSecureCoding:YES error:error]; if (!payload) return NO; __block BOOL result=NO; dispatch_sync(self.queue, ^{ const char *sql="INSERT INTO Documents(document_id,content_hash,payload,updated_at) VALUES(?,?,?,?) ON CONFLICT(document_id) DO UPDATE SET content_hash=excluded.content_hash,payload=excluded.payload,updated_at=excluded.updated_at"; sqlite3_stmt *stmt=NULL; if (sqlite3_prepare_v2(self.database,sql,-1,&stmt,NULL)==SQLITE_OK) { sqlite3_bind_text(stmt,1,document.documentID.UTF8String,-1,SQLITE_TRANSIENT); sqlite3_bind_text(stmt,2,document.contentHash.UTF8String,-1,SQLITE_TRANSIENT); sqlite3_bind_blob(stmt,3,payload.bytes,(int)payload.length,SQLITE_TRANSIENT); sqlite3_bind_double(stmt,4,NSDate.date.timeIntervalSince1970); result=sqlite3_step(stmt)==SQLITE_DONE; } if (stmt) sqlite3_finalize(stmt); }); if (!result && error) *error=GDTDatabaseError(self.database,@"Save document"); return result; }
- (GDTDocument *)documentForID:(NSString *)documentID contentHash:(NSString *)contentHash error:(NSError **)error { __block GDTDocument *document=nil; dispatch_sync(self.queue, ^{ sqlite3_stmt *stmt=NULL; if (sqlite3_prepare_v2(self.database,"SELECT payload FROM Documents WHERE document_id=? AND content_hash=?",-1,&stmt,NULL)==SQLITE_OK) { sqlite3_bind_text(stmt,1,documentID.UTF8String,-1,SQLITE_TRANSIENT); sqlite3_bind_text(stmt,2,contentHash.UTF8String,-1,SQLITE_TRANSIENT); if (sqlite3_step(stmt)==SQLITE_ROW) { NSData *data=[NSData dataWithBytes:sqlite3_column_blob(stmt,0) length:(NSUInteger)sqlite3_column_bytes(stmt,0)]; NSSet *classes=[NSSet setWithObjects:GDTDocument.class,GDTContentNode.class,GDTSection.class,GDTParagraph.class,GDTSentence.class,GDTWord.class,NSArray.class,NSDictionary.class,NSString.class, nil]; document=[NSKeyedUnarchiver unarchivedObjectOfClasses:classes fromData:data error:error]; } } if (stmt) sqlite3_finalize(stmt); }); return document; }
- (GDTReadingSession *)sessionForDocument:(NSString *)documentID { __block NSData *data=nil; dispatch_sync(self.queue, ^{ sqlite3_stmt *stmt=NULL; if (sqlite3_prepare_v2(self.database,"SELECT payload FROM ReadingSessions WHERE document_id=?",-1,&stmt,NULL)==SQLITE_OK) { sqlite3_bind_text(stmt,1,documentID.UTF8String,-1,SQLITE_TRANSIENT); if (sqlite3_step(stmt)==SQLITE_ROW) data=[NSData dataWithBytes:sqlite3_column_blob(stmt,0) length:(NSUInteger)sqlite3_column_bytes(stmt,0)]; } if (stmt) sqlite3_finalize(stmt); }); GDTReadingSession *session=data ? [NSKeyedUnarchiver unarchivedObjectOfClass:GDTReadingSession.class fromData:data error:nil] : nil; if (!session) { session=[GDTReadingSession new]; session.documentID=documentID; session.rate=0.5f; } return session; }
- (void)saveSession:(GDTReadingSession *)session { NSData *data=[NSKeyedArchiver archivedDataWithRootObject:session requiringSecureCoding:YES error:nil]; if (!data) return; dispatch_async(self.queue, ^{ sqlite3_stmt *stmt=NULL; if (sqlite3_prepare_v2(self.database,"INSERT INTO ReadingSessions(document_id,payload,updated_at) VALUES(?,?,?) ON CONFLICT(document_id) DO UPDATE SET payload=excluded.payload,updated_at=excluded.updated_at",-1,&stmt,NULL)==SQLITE_OK) { sqlite3_bind_text(stmt,1,session.documentID.UTF8String,-1,SQLITE_TRANSIENT); sqlite3_bind_blob(stmt,2,data.bytes,(int)data.length,SQLITE_TRANSIENT); sqlite3_bind_double(stmt,3,NSDate.date.timeIntervalSince1970); sqlite3_step(stmt); } if (stmt) sqlite3_finalize(stmt); }); }
- (void)saveBookmarkForDocument:(NSString *)documentID sentenceIndex:(NSUInteger)index { GDTPlaybackPosition *p=[GDTPlaybackPosition new]; p.documentID=documentID; p.sentenceIndex=index; p.timestamp=NSDate.date; [self saveBookmark:p]; }
- (void)saveBookmark:(GDTPlaybackPosition *)p { dispatch_async(self.queue, ^{ sqlite3_stmt *stmt=NULL; if (sqlite3_prepare_v2(self.database,"INSERT OR REPLACE INTO Bookmarks(document_id,paragraph_index,sentence_index,word_index,character_offset,scroll_offset,progress,timestamp) VALUES(?,?,?,?,?,?,?,?)",-1,&stmt,NULL)==SQLITE_OK) { sqlite3_bind_text(stmt,1,p.documentID.UTF8String,-1,SQLITE_TRANSIENT); sqlite3_bind_int(stmt,2,(int)p.paragraphIndex); sqlite3_bind_int(stmt,3,(int)p.sentenceIndex); sqlite3_bind_int(stmt,4,(int)p.wordIndex); sqlite3_bind_int(stmt,5,(int)p.characterOffset); sqlite3_bind_double(stmt,6,p.scrollOffset); sqlite3_bind_double(stmt,7,p.progress); sqlite3_bind_double(stmt,8,p.timestamp.timeIntervalSince1970); sqlite3_step(stmt); } if (stmt) sqlite3_finalize(stmt); }); }
- (NSArray<NSNumber *> *)bookmarksForDocument:(NSString *)documentID { __block NSMutableArray *result=[NSMutableArray array]; dispatch_sync(self.queue, ^{ sqlite3_stmt *stmt=NULL; if (sqlite3_prepare_v2(self.database,"SELECT sentence_index FROM Bookmarks WHERE document_id=? ORDER BY timestamp DESC",-1,&stmt,NULL)==SQLITE_OK) { sqlite3_bind_text(stmt,1,documentID.UTF8String,-1,SQLITE_TRANSIENT); while (sqlite3_step(stmt)==SQLITE_ROW) [result addObject:@(sqlite3_column_int(stmt,0))]; } if (stmt) sqlite3_finalize(stmt); }); return result; }
- (NSArray<GDTPlaybackPosition *> *)bookmarkPositionsForDocument:(NSString *)documentID { __block NSMutableArray *result=[NSMutableArray array]; dispatch_sync(self.queue, ^{ sqlite3_stmt *stmt=NULL; if (sqlite3_prepare_v2(self.database,"SELECT paragraph_index,sentence_index,word_index,character_offset,scroll_offset,progress,timestamp FROM Bookmarks WHERE document_id=? ORDER BY timestamp DESC",-1,&stmt,NULL)==SQLITE_OK) { sqlite3_bind_text(stmt,1,documentID.UTF8String,-1,SQLITE_TRANSIENT); while (sqlite3_step(stmt)==SQLITE_ROW) { GDTPlaybackPosition *p=[GDTPlaybackPosition new]; p.documentID=documentID; p.paragraphIndex=sqlite3_column_int(stmt,0); p.sentenceIndex=sqlite3_column_int(stmt,1); p.wordIndex=sqlite3_column_int(stmt,2); p.characterOffset=sqlite3_column_int(stmt,3); p.scrollOffset=sqlite3_column_double(stmt,4); p.progress=sqlite3_column_double(stmt,5); p.timestamp=[NSDate dateWithTimeIntervalSince1970:sqlite3_column_double(stmt,6)]; [result addObject:p]; } } if (stmt) sqlite3_finalize(stmt); }); return result; }
- (void)recordHistoryForDocument:(NSString *)documentID position:(GDTPlaybackPosition *)position { NSData *data=[NSKeyedArchiver archivedDataWithRootObject:position requiringSecureCoding:YES error:nil]; if (!data) return; dispatch_async(self.queue, ^{ sqlite3_stmt *stmt=NULL; if (sqlite3_prepare_v2(self.database,"INSERT INTO History(document_id,payload,created_at) VALUES(?,?,?)",-1,&stmt,NULL)==SQLITE_OK) { sqlite3_bind_text(stmt,1,documentID.UTF8String,-1,SQLITE_TRANSIENT); sqlite3_bind_blob(stmt,2,data.bytes,(int)data.length,SQLITE_TRANSIENT); sqlite3_bind_double(stmt,3,NSDate.date.timeIntervalSince1970); sqlite3_step(stmt); } if (stmt) sqlite3_finalize(stmt); }); }
- (NSArray<GDTPlaybackPosition *> *)historyForDocument:(NSString *)documentID limit:(NSUInteger)limit { __block NSMutableArray *result=[NSMutableArray array]; dispatch_sync(self.queue, ^{ sqlite3_stmt *stmt=NULL; if (sqlite3_prepare_v2(self.database,"SELECT payload FROM History WHERE document_id=? ORDER BY created_at DESC LIMIT ?",-1,&stmt,NULL)==SQLITE_OK) { sqlite3_bind_text(stmt,1,documentID.UTF8String,-1,SQLITE_TRANSIENT); sqlite3_bind_int(stmt,2,(int)MAX(1,limit)); while (sqlite3_step(stmt)==SQLITE_ROW) { NSData *data=[NSData dataWithBytes:sqlite3_column_blob(stmt,0) length:(NSUInteger)sqlite3_column_bytes(stmt,0)]; GDTPlaybackPosition *p=[NSKeyedUnarchiver unarchivedObjectOfClass:GDTPlaybackPosition.class fromData:data error:nil]; if (p) [result addObject:p]; } } if (stmt) sqlite3_finalize(stmt); }); return result; }
- (GDTSettings *)settings { __block NSData *data=nil; dispatch_sync(self.queue, ^{ sqlite3_stmt *stmt=NULL; if (sqlite3_prepare_v2(self.database,"SELECT payload FROM Settings WHERE id=1",-1,&stmt,NULL)==SQLITE_OK && sqlite3_step(stmt)==SQLITE_ROW) data=[NSData dataWithBytes:sqlite3_column_blob(stmt,0) length:(NSUInteger)sqlite3_column_bytes(stmt,0)]; if (stmt) sqlite3_finalize(stmt); }); return data ? ([NSKeyedUnarchiver unarchivedObjectOfClass:GDTSettings.class fromData:data error:nil] ?: [GDTSettings new]) : [GDTSettings new]; }
- (void)saveSettings:(GDTSettings *)settings { NSData *data=[NSKeyedArchiver archivedDataWithRootObject:settings requiringSecureCoding:YES error:nil]; if (!data) return; dispatch_async(self.queue, ^{ sqlite3_stmt *stmt=NULL; if (sqlite3_prepare_v2(self.database,"INSERT OR REPLACE INTO Settings(id,payload) VALUES(1,?)",-1,&stmt,NULL)==SQLITE_OK) { sqlite3_bind_blob(stmt,1,data.bytes,(int)data.length,SQLITE_TRANSIENT); sqlite3_step(stmt); } if (stmt) sqlite3_finalize(stmt); }); }
- (void)recordStatisticsForDocument:(NSString *)documentID seconds:(NSTimeInterval)seconds words:(NSUInteger)words { dispatch_async(self.queue, ^{ sqlite3_stmt *stmt=NULL; if (sqlite3_prepare_v2(self.database,"INSERT INTO Statistics(document_id,seconds,words,sessions) VALUES(?,?,?,1) ON CONFLICT(document_id) DO UPDATE SET seconds=seconds+excluded.seconds,words=words+excluded.words,sessions=sessions+1",-1,&stmt,NULL)==SQLITE_OK) { sqlite3_bind_text(stmt,1,documentID.UTF8String,-1,SQLITE_TRANSIENT); sqlite3_bind_double(stmt,2,seconds); sqlite3_bind_int(stmt,3,(int)words); sqlite3_step(stmt); } if (stmt) sqlite3_finalize(stmt); }); }
@end
