default_platform(:ios)

platform :ios do
  desc "Run unit and UI tests"
  lane :test do
    scan(scheme: "LightNovelReader")
  end

  desc "Build IPA for Ad-Hoc distribution"
  lane :build_ipa do
    match(type: "adhoc")
    gym(
      scheme: "LightNovelReader",
      export_method: "ad-hoc",
      output_directory: "./build",
      output_name: "LightNovelReader.ipa"
    )
  end
  
  desc "Push to TestFlight"
  lane :beta do
    match(type: "appstore")
    gym(scheme: "LightNovelReader")
    pilot
  end
end
