name: Build iOS IPA

on:
  push:
    branches: [ master, main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-15

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Run Build Script
        run: bash build_native.sh

      - name: Upload IPA Artifact
        uses: actions/upload-artifact@v4
        with:
          name: LightNovelReader-iOS-IPA
          path: build/app.ipa
